// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S4_Progra_Web.Server.Data;

#nullable disable

namespace S4_Progra_Web.Server.Migrations
{
    [DbContext(typeof(DBCubesContext))]
    [Migration("20230519025620_withdualkey")]
    partial class withdualkey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("S4_Progra_Web.Shared.Modelos.Cube", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Cubes");
                });

            modelBuilder.Entity("S4_Progra_Web.Shared.Modelos.CubePedidos", b =>
                {
                    b.Property<int>("CubeId")
                        .HasColumnType("int");

                    b.Property<int>("PedidosId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PrecioVenta")
                        .HasColumnType("int");

                    b.HasKey("CubeId", "PedidosId");

                    b.HasIndex("PedidosId");

                    b.ToTable("CubePedidos");
                });

            modelBuilder.Entity("S4_Progra_Web.Shared.Modelos.Pedidos", b =>
                {
                    b.Property<int>("PedidosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidosId"));

                    b.Property<string>("PedidosDireccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidosEstado")
                        .HasColumnType("int");

                    b.Property<DateTime>("PedidosFecha")
                        .HasColumnType("datetime2");

                    b.HasKey("PedidosId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("S4_Progra_Web.Shared.Modelos.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("ProveedorCorreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProveedor");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("S4_Progra_Web.Shared.Modelos.Cube", b =>
                {
                    b.HasOne("S4_Progra_Web.Shared.Modelos.Proveedor", "ProveedorData")
                        .WithMany("Cubos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProveedorData");
                });

            modelBuilder.Entity("S4_Progra_Web.Shared.Modelos.CubePedidos", b =>
                {
                    b.HasOne("S4_Progra_Web.Shared.Modelos.Cube", "CubeData")
                        .WithMany()
                        .HasForeignKey("CubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S4_Progra_Web.Shared.Modelos.Pedidos", "PedidosData")
                        .WithMany("OrderDetails")
                        .HasForeignKey("PedidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CubeData");

                    b.Navigation("PedidosData");
                });

            modelBuilder.Entity("S4_Progra_Web.Shared.Modelos.Pedidos", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("S4_Progra_Web.Shared.Modelos.Proveedor", b =>
                {
                    b.Navigation("Cubos");
                });
#pragma warning restore 612, 618
        }
    }
}
